version: "3"

networks:
  giftbox.net:
    driver: bridge

services:
  web:
    image: canals/php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "18080:80"
    volumes :
      - ./public:/var/www/html
      - ./img:/var/www/html/img
      - ./src:/var/www/src
    working_dir: /var/www/src
    networks:
      - giftbox.net
    depends_on:
      - sql




#############################
# mysql + adminer / can be replaced by mariadb
#############################
  sql:
   image: mysql:latest
   environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}

   ports:
     - "18082:3306"
   networks:
     giftbox.net:
        aliases:
          - sql.db

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: sql
      PMA_PORT: 3306
    ports:
      - "18081:80"
    networks:
      - giftbox.net
    depends_on:
      - sql